### ISSUE TITLE
Question about multiple ACI containers

### ISSUE THREAD

**Issue by JuanCarlosV** [tmeckel/aci-dns-manager#5]
do i have to extend my container images to add the script like in your example to every container I want to get a static private ip address?

**Comment by tmeckel** [comment]
@JuanCarlosV sorry for the late answer! My understanding is that for every container group one IP address (public or private) is assigned, regardless if you use a multi-container group with sidecars or a single-container group. 

![container-groups-example](https://github.com/tmeckel/aci-dns-manager/assets/14177833/7e51a2ae-62c3-4193-a34d-87e1f736b7d0)

You should add an `s6init` configuration at least for every primary container of the group (first container in the group), so that the private IP address can be mapped to a DNS A record. Never tested if a configuration in a sidecar would work. 

# References:
- [What is a container group?](https://learn.microsoft.com/en-us/azure/container-instances/container-instances-container-groups#what-is-a-container-group)
- [Tutorial: Deploy a multi-container group using a YAML file](https://learn.microsoft.com/en-us/azure/container-instances/container-instances-multi-container-yaml)
